application:
  subdomain: suwayomi
  background_task: true
  multi_instance: false
  public_path:
    - /
    - /resolver
  upstreams:
    - location: /
      backend: http://suwayomi:4567/
    - location: /resolver
      backend: http://flaresolverr:8191/
services:
  suwayomi:
    # upstream: ghcr.io/suwayomi/suwayomi-server:v2.3.2361
    image: ghcr.1ms.run/suwayomi/suwayomi-server:v2.3.2361
    environment:
      - TZ=Asia/Shanghai
      - FLARESOLVERR_ENABLED=true
      - FLARESOLVERR_URL=/resolver
      - UID=1037
      - GID=100
    binds:
      - /lzcapp/var/Tachidesk:/home/suwayomi/.local/share/Tachidesk
    setup_script: |
      mkdir -p /lzcapp/var/Tachidesk
      chmod 777 /lzcapp/var/Tachidesk
  flaresolverr:
    # upstream: ghcr.io/thephaseless/byparr:latest
    image: ghcr.1ms.run/thephaseless/byparr:latest@sha256:51a629fa3dcde0cee1a780922e1a572c4a5be0b5a0cb825db73d4e63059275ff
    environment:
      - TZ=Asia/Shanghai
